### ISSUE TITLE
Using the selenium:vnc - nothing shows?

### ISSUE THREAD

**Issue by ratnose** [labs42io/web-automation#12]
So in my attempt to understand why I am not reaching an element I thought I would look at what is happening.
So I stopped selenium and started selenium:vnc, used a VNCviewer to connect to 127.0.0.1:5900 / 5901.
I do see a Ubuntu logo and a taskbar but that it is, then I run the tests nothing happens on the VNC "screen"
What have I missed?

**Comment by ratnose** [comment]
I know what I missed - ignore this.

**Comment by alkanna** [comment]
@ratnose You know that there is nothing worse in issue tracking than "Something's wrong" - "Nvm fixed it" and then closed.
What did you do to fix it?
