### ISSUE TITLE
pause for XXXXms - not working?

### ISSUE THREAD

**Issue by ratnose** [labs42io/web-automation#13]
I need to use pauses in my test and glad to find pause, added:
And I pause for 3000ms

When I look at the test through VNC, there is no 3 sec pause what so ever.
That is why my test fails.

**Comment by dimadeveatii** [comment]
There is a test ensures it works and it passes:

```gherkin
Scenario: pause
        Given I open the url "http://webdriverjs.christian-bromann.com/"
        And   there is no element ".lateElem" on the page
        When  I pause for 3000ms
        Then  I expect that element ".lateElem" is displayed
```

Make sure you use it correctly.
