### ISSUE TITLE
In clickElement.ts - Chrome adds a = to a selector, Firefox doesnt

### ISSUE THREAD

**Issue by ratnose** [labs42io/web-automation#14]
In my feature file I have the line:
Then I click on the link "Biografer"

Chrome can't find the link due to the selector is named "=Biografer", Firefox finds it perfectly since it uses the name on the link as "Biografer".

Does Firefox and Chrome interpit typescript diffrently?

**Comment by dimadeveatii** [comment]
Please paste entire test that reproduces the issue.
