### ISSUE TITLE
Help: executing tests on windows

### ISSUE THREAD

**Issue by starostin13** [labs42io/web-automation#15]
Hi guys,
Have I chance to execute tests without docker? Directly on my PC? Or I should create a docker image for that? Sry about had to create issue for dump question.

**Comment by dimadeveatii** [comment]
Hi @starostin13 ,

You need docker installed on your computer to be able to run tests. But there is no need to create docker images. 
Please see the [quick start](https://github.com/labs42io/web-automation#quick-start) section.

**Comment by starostin13** [comment]
Hi @dimadeveatii 
I mean execute on windows chrome/firefox not on linux chrome/firefox

**Comment by dimadeveatii** [comment]
> I mean execute on windows chrome/firefox not on linux chrome/firefox

Currently it uses docker selenium images for running chrome and firefox, those are based on docker linux images.
But why would you want to run tests against windows chrome/firefox? The only reason for doing that is in case of some browser OS specific functionality or issue. 
And note that you don't need firefox or chrome installed locally.
