### ISSUE TITLE
How to run using local browsers using 'selenium-standalone' service.

### ISSUE THREAD

**Issue by ankit-ranjan** [labs42io/web-automation#16]
Hi,

Please help to run the setup on locally installed browsers using 'selenium-standalone' service. Currently I am getting below error:
ERROR @wdio/utils:initialiseServices: TypeError: Cannot read property 'outputDir' of undefined

Also, getting the below error along with the above one:
ERROR webdriver: Request failed due to Error: connect ECONNREFUSED 127.0.0.1:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

Thanks,
Ankit Ranjan

**Comment by dimadeveatii** [comment]
This repository is about running selenium and browsers in docker selenium containers.
