### ISSUE TITLE
[question] Run multiple time

### ISSUE THREAD

**Issue by starostin13** [labs42io/web-automation#18]
Hi there,

I have a 2 question today
1) Can I run test multiple time due to N or due to they succeeded?
2) Can I run test on several nodes?

Thanks, In advice

**Comment by dimadeveatii** [comment]
Hi @starostin13 ,

> Can I run test multiple time due to N or due to they succeeded?

in his repo there is no support for this, but you could handle this via a custom `then` snippen.

> Can I run test on several nodes?

by default tests run on chrome and firefox browser nodes in parallel.
