### ISSUE TITLE
Not an issue really but how do I get the right xpath?

### ISSUE THREAD

**Issue by ratnose** [labs42io/web-automation#5]
I know... bad of me using issues as support, but Ive been trying to use xpath to point at elements that the system otherwise refuses to find.

Then  I expect that element "*" is displayed

But the ones from Chrome doesn't work:
//*[@id="inpPointFrMobile"] 
Expected element "//*[@id='inpPointFrMobile']" to be displayed: expected false to equal true
or /html/body/div[4]/div/div/div[2]/form/fieldset/div[1]/div[1]/input
Error: Expected element "/html/body/div[4]/div/div/div[2]/form/fieldset/div[1]/div[1]/input" to be displayed: expected false to equal true

Then I tried Firefox's and the same result there.
//*[@id="inpPointFrMobile"]
Expected element "//*[@id='inpPointFrMobile']" to be displayed: expected false to equal true

So what shall I do to make it work? For sometimes xpath is the only solution.
In your example there is an possibility to test a positive with elements.

**Comment by dimadeveatii** [comment]
See the WebdriverIO's official [documentation](https://webdriver.io/docs/selectors.html#xpath) on searching using xPath queries.

**Comment by dimadeveatii** [comment]
But why xPath is the only solution? CSS selectors are supported and are very powerful. See [:nth-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) for example.
My advice is to first try to find a selector that returns the desired element using `document.querySelector(...)` in the browser console.

**Comment by ratnose** [comment]
I have a hard time reaching a element on a page.
The page in question is: https://www.dintur.se/navigation/sok-resa/
It is a Wordpress page, I want to reach the first inputfield.

So far xpath has failed, id has failed so far I haven't tried nth child but... full xpath gives me shivers.
I will be using this on many WP sites so this will help me a lot.

**Comment by dimadeveatii** [comment]
This happens because your input is inside an `iframe`. There was no cucumber support for switching to an iframe, but I've just pushed it. If you get the latest changes, then this should work (I checked it):
```gherkin
Feature: Set an input inside an iframe

    As a user that opens a page
    I want to be able to change an input inside an iframe

    Background:
      Given I open the url "https://www.dintur.se/navigation/sok-resa/"

    Scenario: Update first input field
      When I switch to iframe "iframe"
        And I set "test 42" to the inputfield "#inpPointFrMobile"
      Then I expect that element "#inpPointFrMobile" matches the text "test 42"

```
