### ISSUE TITLE
After a few runs the app 'crashes'...

### ISSUE THREAD

**Issue by ratnose** [labs42io/web-automation#6]
I am adding features to my feature files, after lets say 5 runs of npm run test, I get a lot of errors:
Multiple step definitions match:
  /^I open the (url|site) "([^"]*)?"$/ - src/steps/given 3.ts:23

They all contain "Multiple step definitions match" the only way I have managed to get rid of them is to re-clone the repo and start from the beginning.

In the steps directory there are multiple steps files.
given.ts
given 3.ts
...

**Comment by dimadeveatii** [comment]
That happens because probably you copy/pasted some of the files from `src/steps` (`src/steps/given 3.ts` I guess is copied from `src/steps/given.ts`). All `*.ts` files inside `src/steps` are loaded automatically.

**Comment by ratnose** [comment]
Thing is I haven't. I don't touch the steps files at all.
Strange thing also was that an old feature-file I deleted came back as well.
All I did was a pull to update to get the iframe adding and it was not from my fork.

**Comment by dimadeveatii** [comment]
You mentioned `src/steps/given 3.ts` which is not in this repository. There are no scripts/tasks that could copy or generate them.
