### ISSUE TITLE
Dockerfile unused?

### ISSUE THREAD

**Issue by manuschillerdev** [labs42io/web-automation#8]
Hi, thanks for your great work.
Is it possible that the Dockerfile is currently unused? 
As far as I can tell the docker-compose files don't use it in any way, right?

**Comment by dimadeveatii** [comment]
Hi, thanks for appreciation. 
Dockerfile is used for CI, see `docker-compose.ci.yml`.

**Comment by manuschillerdev** [comment]
i see, thanks!!
