### ISSUE TITLE
App crashed... 

### ISSUE THREAD

**Issue by ratnose** [labs42io/web-automation#9]
Hard to write a title for this.
So I installed web-automation last Friday all was working perfectly then.
I thought I would run the tests again this morning.
First off it is this error that I have no clue why it appears with multiple step definitions appearing from nowhere.
Then I had an idea that it was the docker containers that were missing so I restarted them and ran the tests again then this was the error I got:
[0-0] 2020-03-16T08:48:25.354Z ERROR webdriver: Request failed due to unknown error: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, cjson:metadata: {device: 3.141.59-zirconium}, goog:chromeOptions: {args: [--no-sandbox, --headless, --disable-gpu]}}

To get it to work I need to reinstall everything. Or so I thought.
I tried to remove the web-automation directory and cloning it again, and running all the npm stuff. Still the same error as the one above.

**Comment by dimadeveatii** [comment]
If you see above error, try running `npm run selenium:stop` it will remove the docker containers and associated volumes so that when you start again, it will use new containers.

**Comment by dimadeveatii** [comment]
It could also happen due to busy ports, see maybe [this](https://github.com/SeleniumHQ/selenium/issues/2043) related selenium issue.

**Comment by ratnose** [comment]
I had to remove the repo, manually uninstall all the npm packages, restart my computer - to get it to work.
(psst have you seen a mail from me?)
